name: Keepalive

on:
  # At 8:40 AM UTC, on day 25 of the month
  schedule:
    - cron: '40 8 25 * *'
  workflow_dispatch:

jobs:
  keepalive:
    name: Keepalive
    # Only run cron on the silverstripe-themes account
    if: (github.event_name == 'schedule' && github.repository_owner == 'silverstripe-themes') || (github.event_name != 'schedule')
    runs-on: ubuntu-latest
    steps:
      - name: Keepalive
        uses: silverstripe/gha-keepalive@v1
